site_name: nescience
theme:
  name: material
repo_url: https://github.com/rleiva/nescience
nav:
  - Home: index.md
  - API:
    - Metrics: api/metrics.md
    - Estimators: api/estimators.md
    - Search: api/search.md
docs_dir: docs
site_dir: site
markdown_extensions:
  - admonition
  - toc:
      permalink: true
      toc_depth: 3
